--Customers tablosundan adi 'A' harfi ile bașlayan kiŞileri çeken sorguyu yaziniz.

SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%'

--Customers tablosundan adi ‘A’ harfi ile baslayan erkek misterileri ceken sorguyu yaziniz.

SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%'
AND GENDER='E'

--1990 ve 1995 yillari arasinda dogan misterileri gekiniz. 1990 ve 1995yillari dahildir.
SELECT * FROM CUSTOMERS
WHERE BIRTHDATE>='1990-01-01'
AND BIRTHDATE<='1995-12-31'

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN
'1990-01-01' AND '1995-12-31'

SELECT * FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) >=1990
AND YEAR(BIRTHDATE)<=1995 

SELECT * FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) BETWEEN 1990 AND 1995
 
--istanbul’da yasayan kisileri Join kullanarak getiren sorguyu yaziniz.

SELECT C.*,CT.CITY FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID=CT.ID
WHERE CT.CITY='İSTANBUL'

--istanbul’da yasayan kisileri subquery kullanarak getiren sorguyu
yaziniz.

SELECT
(SELECT CITY FROM CITIES WHERE ID=C.CITYID),
* FROM CUSTOMERS C
WHERE
(SELECT CITY FROM CITIES WHERE ID=C.CITYID)='İSTANBUL'


--Hangi sehirde kaç musterimizin oldugu bilgisini getiren sorguyu yaziniz.

SELECT CT.CITY, COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
GROUP BY CT.CITY
--YUKARIDAKİ 0 OLAN DEĞERLERİ VERMEZ
SELECT CT.CITY, COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
LEFT JOIN CITIES CT ON CT.ID=C.CITYID
GROUP BY CT.CITY


--SUBQUERY İLE
SELECT *,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = CT.ID) AS CUSTOMERCOUNT
FROM CITIES CT

--10’dan fazla müşterimiz olan şehirleri müşteri sayısı ile birlikte müşteri sayısına göre fazladan aza doğru sıralı şekilde getiriniz.

SELECT CT.CITY,COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
GROUP  BY CT.CITY
HAVING COUNT(C.ID)>10
ORDER BY CUSTOMERCOUNT DESC

--SUBQUERY İLE

SELECT CITY,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID) AS CUSTOMERNUMBER
 FROM CITIES C
WHERE 
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID)>10
ORDER BY 2 DESC


--Hangi şehirde kaç erkek, kaç kadın müşterimizin olduğu bilgisini getiren sorgu yazınız.
--ALT ALTA
SELECT CT.CITY,C.GENDER,COUNT(C.ID) AS CUSTOMERCOUNT
FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
GROUP BY CT.CITY,C.GENDER
ORDER BY CT.CITY,C.GENDER
--YAN YANA
SELECT CITY,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID) AS CUSTOMERCOUNT,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID AND GENDER='E') AS MALECUSTOMERCOUNT,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID AND GENDER='K') AS FEMALECUSTOMERCOUNT
FROM CITIES C

--Customers tablosuna yaş grubu için yeni alan ekleyiniz. Bu işlemi hem management studio ile hem de sql kodu ile yapınız.
--Alan adı AGEGROUP veritipi Varchar(50)

ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(50)

--Customers tablosuna eklediğiniz AGEGROUP alanını 20-35 yaş arası, 46-55 yaş arası,55-65 yaş arası ve 65 yaş üstü olarak güncelleyiniz.

SELECT 
DATEDIFF(YEAR,BIRTHDATE,GETDATE()),
* FROM CUSTOMERS

UPDATE CUSTOMERS SET AGEGROUP='20-35 AGE'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35


UPDATE CUSTOMERS SET AGEGROUP='36-45 AGE'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45


UPDATE CUSTOMERS SET AGEGROUP='46-55 AGE'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55


UPDATE CUSTOMERS SET AGEGROUP='55-65 AGE'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65


UPDATE CUSTOMERS SET AGEGROUP='65+ AGE'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65

--Customers tablosunda yaş aralıklarındaki müşteri sayılarını gösteriniz. ( NOT: AGEGROUP alanını kullanmadan sorgu getirecektir.)
--AGEGROUP kullanarak yapılınca bu şekilde oluyor.
SELECT AGEGROUP, COUNT(*) FROM CUSTOMERS
GROUP BY AGEGROUP
ORDER BY AGEGROUP

--AGEGROUP kullanmadan

SELECT 

CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65+ AGE'
END AGEGROUP,
COUNT(*) CUSTOMERCOUNT
FROM CUSTOMERS
GROUP BY 
 CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65+ AGE'
END 
 
 ORDER BY AGEGROUP

--DYNAMIC VİEW ile yapımı
 SELECT AGEGROUP2,COUNT(TMP.ID) AS CUSTOMERCOUNT FROM
 (
SELECT *,

CASE
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 AGE'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65+ AGE'

END AGEGROUP2
FROM CUSTOMERS) TMP
GROUP BY AGEGROUP2
ORDER BY AGEGROUP2

--İstanbul'da yaşayıp ilçesi 'Kadıköy' dışında olanları listeleyiniz.